CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE
  auth (
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id TEXT UNIQUE,
    CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
  );