version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: api-book-wise
      POSTGRES_PASSWORD: api-book-wise
      POSTGRES_DB: api-book-wise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: